services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
  cart:
    image: cart
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8080"
      - "8083:8082"
    depends_on:
      - loms
      - db
  loms:
    image: loms
    build:
      context: .
      dockerfile: ./loms/Dockerfile
    env_file:
      - .env
    ports:
      - "8084:8080"
      - "8085:8082"
    depends_on:
      - db
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
