syntax = "proto3";

package cart.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/KEKACIK/ozon-univer-golang/api/cart/v1;cart";
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Ozon Univer Golang (cart)"
    version: "0.0.1"
  }
  schemes: HTTP
  schemes: HTTPS
  consumes: "application/json"
  produces: "application/json"
};

service CartService {
  rpc ItemAdd(ItemAddRequest) returns (ItemAddResponse) {
    option (google.api.http) = {
      post: "/cart/item/add"
      body: "*"
    };
  }

  rpc ItemDelete(ItemDeleteRequest) returns (ItemDeleteResponse) {
    option (google.api.http) = {
      post: "/cart/item/delete"
      body: "*"
    };
  }

  rpc List(ListRequest) returns (ListResponse) {
    option (google.api.http) = {
      post: "/cart/list"
      body: "*"
    };
  }

  rpc Clear(ClearRequest) returns (ClearResponse) {
    option (google.api.http) = {
      post: "/cart/clear"
      body: "*"
    };
  }

  rpc Checkout(CheckoutRequest) returns (CheckoutResponse) {
    option (google.api.http) = {
      post: "/cart/checkout"
      body: "*"
    };
  }
}

// Item Add

message ItemAddRequest {
  int64 user = 1 [(buf.validate.field).int64.gt = 0];
  uint32 sku = 2 [(buf.validate.field).uint32.gt = 0];
  uint32 count = 3 [(buf.validate.field).uint32.gt = 0];
}

message ItemAddResponse {}

// Item Delete

message ItemDeleteRequest {
  int64 user = 1;
  uint32 sku = 2;
}

message ItemDeleteResponse {}

// List

message ListItem {
  uint32 sku = 2;
  uint32 count = 3;
  string name = 4;
  uint32 price = 5;
}

message ListRequest {
  int64 user = 1 [(buf.validate.field).int64.gt = 0];
}

message ListResponse {
  repeated ListItem items = 1;
  uint32 total_price = 2;
}

// Clear

message ClearRequest {
  int64 user = 1 [(buf.validate.field).int64.gt = 0];
}

message ClearResponse {}

// Checkout

message CheckoutRequest {
  int64 user = 1 [(buf.validate.field).int64.gt = 0];
}

message CheckoutResponse {
  int64 order_id = 1;
}
