// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loms/v1/loms.proto

package loms

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateItem) Reset() {
	*x = OrderCreateItem{}
	mi := &file_loms_v1_loms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateItem) ProtoMessage() {}

func (x *OrderCreateItem) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateItem.ProtoReflect.Descriptor instead.
func (*OrderCreateItem) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateItem) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *OrderCreateItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          int64                  `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Items         []*OrderCreateItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	mi := &file_loms_v1_loms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreateRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *OrderCreateRequest) GetItems() []*OrderCreateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	mi := &file_loms_v1_loms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreateResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderInfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoItem) Reset() {
	*x = OrderInfoItem{}
	mi := &file_loms_v1_loms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoItem) ProtoMessage() {}

func (x *OrderInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoItem.ProtoReflect.Descriptor instead.
func (*OrderInfoItem) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{3}
}

func (x *OrderInfoItem) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *OrderInfoItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoRequest) Reset() {
	*x = OrderInfoRequest{}
	mi := &file_loms_v1_loms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoRequest) ProtoMessage() {}

func (x *OrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoRequest.ProtoReflect.Descriptor instead.
func (*OrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{4}
}

func (x *OrderInfoRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          int64                  `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	Items         []*OrderInfoItem       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_loms_v1_loms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{5}
}

func (x *OrderInfoResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoResponse) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *OrderInfoResponse) GetItems() []*OrderInfoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayRequest) Reset() {
	*x = OrderPayRequest{}
	mi := &file_loms_v1_loms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayRequest) ProtoMessage() {}

func (x *OrderPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayRequest.ProtoReflect.Descriptor instead.
func (*OrderPayRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{6}
}

func (x *OrderPayRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderPayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayResponse) Reset() {
	*x = OrderPayResponse{}
	mi := &file_loms_v1_loms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResponse) ProtoMessage() {}

func (x *OrderPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResponse.ProtoReflect.Descriptor instead.
func (*OrderPayResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{7}
}

type OrderCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelRequest) Reset() {
	*x = OrderCancelRequest{}
	mi := &file_loms_v1_loms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelRequest) ProtoMessage() {}

func (x *OrderCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelRequest.ProtoReflect.Descriptor instead.
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCancelRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelResponse) Reset() {
	*x = OrderCancelResponse{}
	mi := &file_loms_v1_loms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelResponse) ProtoMessage() {}

func (x *OrderCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelResponse.ProtoReflect.Descriptor instead.
func (*OrderCancelResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{9}
}

type GetStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksRequest) Reset() {
	*x = GetStocksRequest{}
	mi := &file_loms_v1_loms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksRequest) ProtoMessage() {}

func (x *GetStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksRequest.ProtoReflect.Descriptor instead.
func (*GetStocksRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{10}
}

func (x *GetStocksRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksResponse) Reset() {
	*x = GetStocksResponse{}
	mi := &file_loms_v1_loms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksResponse) ProtoMessage() {}

func (x *GetStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_loms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksResponse.ProtoReflect.Descriptor instead.
func (*GetStocksResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_loms_proto_rawDescGZIP(), []int{11}
}

func (x *GetStocksResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_loms_v1_loms_proto protoreflect.FileDescriptor

const file_loms_v1_loms_proto_rawDesc = "" +
	"\n" +
	"\x12loms/v1/loms.proto\x12\aloms.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"K\n" +
	"\x0fOrderCreateItem\x12\x19\n" +
	"\x03sku\x18\x01 \x01(\rB\a\xbaH\x04*\x02 \x00R\x03sku\x12\x1d\n" +
	"\x05count\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\x05count\"a\n" +
	"\x12OrderCreateRequest\x12\x1b\n" +
	"\x04user\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x04user\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.loms.v1.OrderCreateItemR\x05items\"0\n" +
	"\x13OrderCreateResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"7\n" +
	"\rOrderInfoItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"6\n" +
	"\x10OrderInfoRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aorderId\"\x88\x01\n" +
	"\x11OrderInfoResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04user\x18\x03 \x01(\x03R\x04user\x12,\n" +
	"\x05items\x18\x04 \x03(\v2\x16.loms.v1.OrderInfoItemR\x05items\"5\n" +
	"\x0fOrderPayRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aorderId\"\x12\n" +
	"\x10OrderPayResponse\"8\n" +
	"\x12OrderCancelRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aorderId\"\x15\n" +
	"\x13OrderCancelResponse\"-\n" +
	"\x10GetStocksRequest\x12\x19\n" +
	"\x03sku\x18\x01 \x01(\rB\a\xbaH\x04*\x02 \x00R\x03sku\"2\n" +
	"\x11GetStocksResponse\x12\x1d\n" +
	"\x05count\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x05count2\xe1\x03\n" +
	"\vLomsService\x12b\n" +
	"\vOrderCreate\x12\x1b.loms.v1.OrderCreateRequest\x1a\x1c.loms.v1.OrderCreateResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/order/create\x12Z\n" +
	"\tOrderInfo\x12\x19.loms.v1.OrderInfoRequest\x1a\x1a.loms.v1.OrderInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/order/info\x12V\n" +
	"\bOrderPay\x12\x18.loms.v1.OrderPayRequest\x1a\x19.loms.v1.OrderPayResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/order/pay\x12b\n" +
	"\vOrderCancel\x12\x1b.loms.v1.OrderCancelRequest\x1a\x1c.loms.v1.OrderCancelResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/order/cancel\x12V\n" +
	"\tGetStocks\x12\x19.loms.v1.GetStocksRequest\x1a\x1a.loms.v1.GetStocksResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/stocksB\x87\x01\x92AL\x12\"\n" +
	"\x19Ozon Univer Golang (loms)2\x050.0.1*\x02\x01\x022\x10application/json:\x10application/jsonZ6github.com/KEKACIK/ozon-univer-golang/api/loms/v1;lomsb\x06proto3"

var (
	file_loms_v1_loms_proto_rawDescOnce sync.Once
	file_loms_v1_loms_proto_rawDescData []byte
)

func file_loms_v1_loms_proto_rawDescGZIP() []byte {
	file_loms_v1_loms_proto_rawDescOnce.Do(func() {
		file_loms_v1_loms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loms_v1_loms_proto_rawDesc), len(file_loms_v1_loms_proto_rawDesc)))
	})
	return file_loms_v1_loms_proto_rawDescData
}

var file_loms_v1_loms_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_loms_v1_loms_proto_goTypes = []any{
	(*OrderCreateItem)(nil),     // 0: loms.v1.OrderCreateItem
	(*OrderCreateRequest)(nil),  // 1: loms.v1.OrderCreateRequest
	(*OrderCreateResponse)(nil), // 2: loms.v1.OrderCreateResponse
	(*OrderInfoItem)(nil),       // 3: loms.v1.OrderInfoItem
	(*OrderInfoRequest)(nil),    // 4: loms.v1.OrderInfoRequest
	(*OrderInfoResponse)(nil),   // 5: loms.v1.OrderInfoResponse
	(*OrderPayRequest)(nil),     // 6: loms.v1.OrderPayRequest
	(*OrderPayResponse)(nil),    // 7: loms.v1.OrderPayResponse
	(*OrderCancelRequest)(nil),  // 8: loms.v1.OrderCancelRequest
	(*OrderCancelResponse)(nil), // 9: loms.v1.OrderCancelResponse
	(*GetStocksRequest)(nil),    // 10: loms.v1.GetStocksRequest
	(*GetStocksResponse)(nil),   // 11: loms.v1.GetStocksResponse
}
var file_loms_v1_loms_proto_depIdxs = []int32{
	0,  // 0: loms.v1.OrderCreateRequest.items:type_name -> loms.v1.OrderCreateItem
	3,  // 1: loms.v1.OrderInfoResponse.items:type_name -> loms.v1.OrderInfoItem
	1,  // 2: loms.v1.LomsService.OrderCreate:input_type -> loms.v1.OrderCreateRequest
	4,  // 3: loms.v1.LomsService.OrderInfo:input_type -> loms.v1.OrderInfoRequest
	6,  // 4: loms.v1.LomsService.OrderPay:input_type -> loms.v1.OrderPayRequest
	8,  // 5: loms.v1.LomsService.OrderCancel:input_type -> loms.v1.OrderCancelRequest
	10, // 6: loms.v1.LomsService.GetStocks:input_type -> loms.v1.GetStocksRequest
	2,  // 7: loms.v1.LomsService.OrderCreate:output_type -> loms.v1.OrderCreateResponse
	5,  // 8: loms.v1.LomsService.OrderInfo:output_type -> loms.v1.OrderInfoResponse
	7,  // 9: loms.v1.LomsService.OrderPay:output_type -> loms.v1.OrderPayResponse
	9,  // 10: loms.v1.LomsService.OrderCancel:output_type -> loms.v1.OrderCancelResponse
	11, // 11: loms.v1.LomsService.GetStocks:output_type -> loms.v1.GetStocksResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_loms_v1_loms_proto_init() }
func file_loms_v1_loms_proto_init() {
	if File_loms_v1_loms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loms_v1_loms_proto_rawDesc), len(file_loms_v1_loms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loms_v1_loms_proto_goTypes,
		DependencyIndexes: file_loms_v1_loms_proto_depIdxs,
		MessageInfos:      file_loms_v1_loms_proto_msgTypes,
	}.Build()
	File_loms_v1_loms_proto = out.File
	file_loms_v1_loms_proto_goTypes = nil
	file_loms_v1_loms_proto_depIdxs = nil
}
