// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loms/v1/stocks.proto

package loms

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksRequest) Reset() {
	*x = GetStocksRequest{}
	mi := &file_loms_v1_stocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksRequest) ProtoMessage() {}

func (x *GetStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_stocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksRequest.ProtoReflect.Descriptor instead.
func (*GetStocksRequest) Descriptor() ([]byte, []int) {
	return file_loms_v1_stocks_proto_rawDescGZIP(), []int{0}
}

func (x *GetStocksRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksResponse) Reset() {
	*x = GetStocksResponse{}
	mi := &file_loms_v1_stocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksResponse) ProtoMessage() {}

func (x *GetStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loms_v1_stocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksResponse.ProtoReflect.Descriptor instead.
func (*GetStocksResponse) Descriptor() ([]byte, []int) {
	return file_loms_v1_stocks_proto_rawDescGZIP(), []int{1}
}

func (x *GetStocksResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_loms_v1_stocks_proto protoreflect.FileDescriptor

const file_loms_v1_stocks_proto_rawDesc = "" +
	"\n" +
	"\x14loms/v1/stocks.proto\x12\aloms.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\"-\n" +
	"\x10GetStocksRequest\x12\x19\n" +
	"\x03sku\x18\x01 \x01(\rB\a\xbaH\x04*\x02 \x00R\x03sku\")\n" +
	"\x11GetStocksResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count2^\n" +
	"\x04Loms\x12V\n" +
	"\tGetStocks\x12\x19.loms.v1.GetStocksRequest\x1a\x1a.loms.v1.GetStocksResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/stocksB4Z2github.com/KEKACIK/ozon-univer-golang/loms/v1;lomsb\x06proto3"

var (
	file_loms_v1_stocks_proto_rawDescOnce sync.Once
	file_loms_v1_stocks_proto_rawDescData []byte
)

func file_loms_v1_stocks_proto_rawDescGZIP() []byte {
	file_loms_v1_stocks_proto_rawDescOnce.Do(func() {
		file_loms_v1_stocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loms_v1_stocks_proto_rawDesc), len(file_loms_v1_stocks_proto_rawDesc)))
	})
	return file_loms_v1_stocks_proto_rawDescData
}

var file_loms_v1_stocks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loms_v1_stocks_proto_goTypes = []any{
	(*GetStocksRequest)(nil),  // 0: loms.v1.GetStocksRequest
	(*GetStocksResponse)(nil), // 1: loms.v1.GetStocksResponse
}
var file_loms_v1_stocks_proto_depIdxs = []int32{
	0, // 0: loms.v1.Loms.GetStocks:input_type -> loms.v1.GetStocksRequest
	1, // 1: loms.v1.Loms.GetStocks:output_type -> loms.v1.GetStocksResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loms_v1_stocks_proto_init() }
func file_loms_v1_stocks_proto_init() {
	if File_loms_v1_stocks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loms_v1_stocks_proto_rawDesc), len(file_loms_v1_stocks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loms_v1_stocks_proto_goTypes,
		DependencyIndexes: file_loms_v1_stocks_proto_depIdxs,
		MessageInfos:      file_loms_v1_stocks_proto_msgTypes,
	}.Build()
	File_loms_v1_stocks_proto = out.File
	file_loms_v1_stocks_proto_goTypes = nil
	file_loms_v1_stocks_proto_depIdxs = nil
}
