// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: loms/v1/stocks.proto

package loms

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetStocksRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetStocksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetStocksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetStocksRequestMultiError, or nil if none found.
func (m *GetStocksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetStocksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sku

	if len(errors) > 0 {
		return GetStocksRequestMultiError(errors)
	}

	return nil
}

// GetStocksRequestMultiError is an error wrapping multiple validation errors
// returned by GetStocksRequest.ValidateAll() if the designated constraints
// aren't met.
type GetStocksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetStocksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetStocksRequestMultiError) AllErrors() []error { return m }

// GetStocksRequestValidationError is the validation error returned by
// GetStocksRequest.Validate if the designated constraints aren't met.
type GetStocksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetStocksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetStocksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetStocksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetStocksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetStocksRequestValidationError) ErrorName() string { return "GetStocksRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetStocksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetStocksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetStocksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetStocksRequestValidationError{}

// Validate checks the field values on GetStocksResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetStocksResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetStocksResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetStocksResponseMultiError, or nil if none found.
func (m *GetStocksResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetStocksResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return GetStocksResponseMultiError(errors)
	}

	return nil
}

// GetStocksResponseMultiError is an error wrapping multiple validation errors
// returned by GetStocksResponse.ValidateAll() if the designated constraints
// aren't met.
type GetStocksResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetStocksResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetStocksResponseMultiError) AllErrors() []error { return m }

// GetStocksResponseValidationError is the validation error returned by
// GetStocksResponse.Validate if the designated constraints aren't met.
type GetStocksResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetStocksResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetStocksResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetStocksResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetStocksResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetStocksResponseValidationError) ErrorName() string {
	return "GetStocksResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetStocksResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetStocksResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetStocksResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetStocksResponseValidationError{}
