// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package carts

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO carts(user_id, sku, count) VALUES ($1, $2, $3) RETURNING id, user_id, sku, count
`

type CreateItemParams struct {
	UserID int32
	Sku    int32
	Count  int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createItem, arg.UserID, arg.Sku, arg.Count)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sku,
		&i.Count,
	)
	return i, err
}
