// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package orders_items

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO orders_items(order_id, sku, count) VALUES ($1, $2, $3) RETURNING id, order_id, sku, count
`

type CreateOrderItemParams struct {
	OrderID int64
	Sku     int32
	Count   int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrdersItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem, arg.OrderID, arg.Sku, arg.Count)
	var i OrdersItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Sku,
		&i.Count,
	)
	return i, err
}

const getByOrderId = `-- name: GetByOrderId :many
SELECT id, order_id, sku, count FROM orders_items WHERE order_id=$1
`

func (q *Queries) GetByOrderId(ctx context.Context, orderID int64) ([]OrdersItem, error) {
	rows, err := q.db.Query(ctx, getByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersItem
	for rows.Next() {
		var i OrdersItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Sku,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
