// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stocks

import (
	"context"
)

const getStocks = `-- name: GetStocks :one
SELECT sku, count, reserved
FROM stocks
WHERE sku=$1
`

func (q *Queries) GetStocks(ctx context.Context, sku int32) (Stock, error) {
	row := q.db.QueryRow(ctx, getStocks, sku)
	var i Stock
	err := row.Scan(&i.Sku, &i.Count, &i.Reserved)
	return i, err
}

const listStocks = `-- name: ListStocks :many
SELECT sku, count, reserved
FROM stocks
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(&i.Sku, &i.Count, &i.Reserved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :exec
UPDATE stocks
SET count=$2,
    reserved=$3
WHERE sku=$1
`

type UpdateStockParams struct {
	Sku      int32
	Count    int32
	Reserved int32
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.Exec(ctx, updateStock, arg.Sku, arg.Count, arg.Reserved)
	return err
}
