// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package orders

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(user_id, Status) VALUES ($1, $2) RETURNING id, user_id, status
`

type CreateOrderParams struct {
	UserID int32
	Status string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Status)
	var i Order
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const getByIdOrder = `-- name: GetByIdOrder :one
SELECT id, user_id, status FROM orders WHERE id=$1
`

func (q *Queries) GetByIdOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getByIdOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const setStatusOrder = `-- name: SetStatusOrder :exec
UPDATE orders SET status=$2 WHERE id=$1
`

type SetStatusOrderParams struct {
	ID     int32
	Status string
}

func (q *Queries) SetStatusOrder(ctx context.Context, arg SetStatusOrderParams) error {
	_, err := q.db.Exec(ctx, setStatusOrder, arg.ID, arg.Status)
	return err
}
